"""Build static Pages-ready product pages from the checked C&H catalog. No dependencies."""
import json,re,html,pathlib,urllib.parse
ROOT=pathlib.Path(__file__).resolve().parents[1]
E=lambda s:html.escape(str(s),quote=True)
BASE='https://realabu.github.io/csefuklima.hu/'
FORM='https://docs.google.com/forms/d/e/1FAIpQLSc7wSz5uLNcMJIU8Bv51nB1pZEFuxP2hqascwZGYpEUpwEgoQ/viewform'
GROUPS={'split':'Split klímák','multi':'Multi rendszerek','hoszivattyu':'Levegő–víz hőszivattyúk','fancoil':'Fan-coilok','ipari':'Ipari klímák','paratlanito':'Párátlanítók','szellozes':'Szellőztetők'}
CAT=json.loads((ROOT/'data/catalog.json').read_text())
FAMILY_COPY={
 'Vital':'Költségtudatos megoldást keres egy helyiség hűtésére és időszakos fűtésére? A Vital családnál érdemes kezdeni a beszélgetést.',
 'Vital Plus':'Egyszerűen használható klímát keres a mindennapokra? A Vital Plus családot hűtési és kiegészítő fűtési igényeihez is átbeszéljük.',
 'Arctic':'Hűtés mellett a fűtés is fontos? Az Arctic családot a téli használat és a helyiség hőigénye alapján is érdemes mérlegelni.',
 'Arctic Plus':'Hűtő-fűtő klímát keres, és a téli üzem is szempont? Az Arctic Plus családot az épület adottságaihoz és a fűtési igényhez igazítjuk.',
 'Daytona':'A készülék megjelenése is számít? A Daytona több színben elérhető, így a teljesítmény mellett az otthon stílusához is választhat.',
 'Supreme':'Rendszeres fűtéshez keres klímát? A Supreme családnál a hatékonyság mellett a téli méretezést is alaposan átbeszéljük.',
 'Supreme Continental':'Hűtés, fűtés és a szobához illő megjelenés: a Supreme Continental család különböző színei közül is választhat.',
 'Majesty':'Arany vagy ezüst készüléket képzel el? A Majesty családnál a megjelenés mellé az igényeinek megfelelő teljesítményt választjuk.',
 'Nature':'Fehér vagy fekete klímát keres, hűtésre és fűtésre is? A Nature család megfelelő változatát a használat és a helyiség alapján ajánljuk.',
 'Konzol':'Ha a magasra szerelt beltéri nem fér el jól, érdemes más elhelyezésben gondolkodni. A konzol klíma alacsonyabb falfelületen is elhelyezhető, a gyári távolságok betartásával.'}
def inquire(p):return '../?'+urllib.parse.urlencode({'keszulek':p['name']})+'#kapcsolat'
def summary(p):
 g=p['group'];t=p['name'].lower();f=p['family']
 if g=='multi':
  if 'kültéri' in t:return 'Több helyiség klímáihoz közös kültéri egység. Önmagában nem teljes rendszer: kompatibilis beltéri egységekkel és megtervezett csövezéssel használható.'
  return 'Egy helyiség beltéri egysége több helyiséges multi rendszerhez. Kompatibilis kültéri egység is szükséges hozzá; önmagában nem teljes klíma.'
 if g=='hoszivattyu':return 'Az otthon vízkörös fűtéséhez kapcsolódó berendezés. A meglévő hőleadók, a hőigény és az elektromos háttér alapján választunk megfelelő rendszert.'
 if g=='fancoil':return 'Vízzel működő hőleadó, amely ventilátorral segíti a helyiség hűtését vagy fűtését. Megfelelő vízkör és hűtő-fűtő rendszer szükséges hozzá.'
 if g=='ipari':return 'Irodába, üzletbe vagy nagyobb térbe tervezhető klímamegoldás. A légelosztást, az elhelyezést és a teljesítményt a helyszínhez méretezzük.'
 if g=='paratlanito':return 'A levegő túl magas páratartalmának csökkentésére szolgál. Párátlanítót keres lakásba vagy más helyiségbe? Beszéljük át a körülményeket.'
 if g=='szellozes':return 'Frisslevegő-ellátáshoz tervezhető berendezés, amely a távozó levegő hőjének egy részét visszanyeri. Nem helyettesíti a klímát vagy a teljes fűtést.'
 return FAMILY_COPY.get(f,'Egy helyiség hűtésére és fűtésére tervezhető C&H klíma. A megfelelő méretet a helyszín adottságai alapján választjuk ki.')
def header(title,description,path):
 return f'''<!doctype html><html lang="hu"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#103e59"><title>{E(title)} — Csefu Klíma</title><meta name="description" content="{E(description)}"><link rel="canonical" href="{BASE+path}"><meta property="og:title" content="{E(title)} — Csefu Klíma"><meta property="og:description" content="{E(description)}"><meta property="og:type" content="website"><link rel="icon" href="../assets/favicon.svg"><link rel="stylesheet" href="../style.css"><script src="../script.js" defer></script></head><body class="subpage"><a class="skip" href="#tartalom">Ugrás a tartalomhoz</a><div class="topline"><div class="wrap"><span>Budapest és Pest vármegye</span><button type="button" data-phone>+36 30 884 2875</button></div></div><header class="header"><div class="wrap nav-wrap"><a class="brand" href="../" aria-label="Csefu Klíma kezdőlap"><span>Csefu<span class="brand-light">Klíma</span><small>GONDOSAN. SZEMÉLYESEN.</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menü <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Fő navigáció"><a href="../#szolgaltatasok">Szolgáltatások</a><a href="../keszulekek/">Készülékek</a><a href="../gondos-klimaszereles/">Gondos szerelés</a><a class="button nav-cta" href="../#kapcsolat">Ajánlatot kérek</a></nav></div></header><main id="tartalom">'''
def footer():
 return '''</main><footer class="footer"><div class="wrap"><a class="footer-brand" href="../">Csefu Klíma</a><p>Mintha magunknak csinálnánk.</p><span>© <span data-year>2026</span> Csefu Klíma</span></div><div class="wrap footer-bottom"><div class="footer-nav"><a href="../#kapcsolat">Kapcsolat és adatvédelem</a><a href="../gondos-klimaszereles/">Gondos klímaszerelés</a><a href="../klima-futesre/">Klímás fűtés</a><a href="../klimatisztitas/">Klímatisztítás</a></div><a href="https://www.facebook.com/csefuklima/" target="_blank" rel="noopener noreferrer">Facebook</a></div></footer><a class="floating-contact" href="https://m.me/csefuklima" target="_blank" rel="noopener noreferrer" aria-label="Üzenet a Csefu Klímának Messengerben">Beszéljünk! <span aria-hidden="true">↗</span></a><p id="phone-status" class="phone-status" role="status" aria-live="polite"></p></body></html>'''
def cta(title='Beszéljük meg, mire van szüksége.',text='A készülékválasztást és a gondos kivitelezést egy kézben tartjuk. Ingyenes helyszíni felmérés, személyes egyeztetés.',link='../#kapcsolat',label='Ajánlatot kérek'):
 return f'<div class="wrap"><div class="wide-cta"><div><h2>{E(title)}</h2><p>{E(text)}</p></div><a class="button" href="{E(link)}">{E(label)}</a></div></div>'
def card(p,prefix='../'):
 title=p['family'];power=p['power'];color=p['color'];ident=p['sku']or 'Teljesítményváltozat'
 photo=f'<img src="{prefix+E(p["image"])}" alt="{E(p["name"])}" width="500" height="500" loading="lazy">'if p.get('image')else '<span aria-hidden="true">❄</span>'
 label=title+' · '+power if power else title
 if color:label+=' · '+color
 return f'''<article class="product catalog-product" data-search="{E(p['name']+' '+p['sku']+' '+p['family'])}" data-group="{p['group']}" data-family="{E(p['family'])}" data-power="{E(power)}"><a class="product-photo" href="{prefix}keszulekek/{p['slug']}.html" tabindex="-1" aria-hidden="true">{photo}</a><div class="product-body"><span class="tag">{GROUPS[p['group']]}</span><h2><a href="{prefix}keszulekek/{p['slug']}.html">C&amp;H {E(label)}</a></h2><p class="sku">{E(ident)}</p><p>{E(summary(p))}</p><a class="button secondary" href="{prefix}keszulekek/{p['slug']}.html">Megnézem a készüléket</a></div></article>'''
def write(path,s):
 f=ROOT/path;f.parent.mkdir(exist_ok=True,parents=True);f.write_text(s)
def detail(p):
 name=p['name'];par=p['params'];features=[];g=p['group']
 if g=='split':features.append('<strong>Egy helyiségre tervezve.</strong> A beltéri és a kültéri együtt alkotja a klímát. Több külön szoba ellátásához más elrendezésre lehet szükség.')
 if g=='multi':features.append('<strong>Rendszerben gondolkodjon.</strong> Az egységek párosíthatóságát, a csőhosszakat és az összteljesítményt együtt ellenőrizzük. A helyiségek eltérő igénye is számít.')
 if g=='hoszivattyu':
  if 'monob' in p['source'].lower()or 'mono' in name.lower():features.append('<strong>Monoblokk kialakítás.</strong> A kültérihez vízoldali csatlakozás tartozik. A fagyvédelem, a csővezetés és a vízkör kialakítása a rendszertervezés része.')
  elif 'kombi' in p['source']:features.append('<strong>Kombi rendszer.</strong> A fűtés és a használati meleg víz igényét is átbeszéljük. A pontos tartálykapacitást és a rendszer tartalmát az ajánlatban rögzítjük.')
  else:features.append('<strong>Összehangolt fűtési rendszer.</strong> A hőszivattyú mellé megfelelő vízkör, hőleadók és szabályozás szükséges. Radiátoros rendszer esetén a szükséges vízhőmérséklet is számít.')
 if g=='fancoil':features.append('<strong>A vízkör része.</strong> A teljesítmény függ a víz hőmérsékletétől és a ventilátor fokozatától. Hűtéshez kondenzvíz-elvezetést is kialakítunk.')
 if g=='ipari':features.append('<strong>Az épülethez igazítva.</strong> Légcsatornás egységnél a légcsatornahálózatot, kazettásnál a mennyezet adottságait is vizsgáljuk. Ezek kialakítása az ajánlat része.')
 if g=='paratlanito':features.append('<strong>A párát csökkenti.</strong> A szoba hőmérséklete és páratartalma befolyásolja, mennyi vizet gyűjt össze. A kiváltó okot, például a szellőzés hiányát is érdemes megvizsgálni.')
 if g=='szellozes':features.append('<strong>Friss levegő, tervezett légcsere.</strong> A méretezést a használathoz és az épülethez igazítjuk. A légutak, a zaj és a karbantartási hozzáférés is fontos.')
 if par.get('Wi-Fi vezérlés')=='igen' or p.get('wifi'):
  features.append('<strong>Telefonról is vezérelhető.</strong> A Wi-Fi kényelmes távoli beállítást tesz lehetővé. A szükséges hálózatot és az alkalmazást az átadáskor egyeztetjük.')
 elif par.get('Wi-Fi vezérlés')=='nem':features.append('<strong>Wi-Fi nélkül szerepel a kínálatban.</strong> Ha távoli vezérlést szeretne, az esetleges kiegészítőről külön kérdezzen.')
 if par.get('Fűtésre optimalizált')=='igen':features.append('<strong>Fűtésre optimalizált változat.</strong> Téli használathoz is mérlegelhető. A leghidegebb napokra szükséges fűtőteljesítményt külön méretezzük.')
 if p['family']=='Arctic Plus':features.append('<strong>Téli használatra is tervezett család.</strong> A gyártói leírás csepptálcafűtést és −25 °C-ig terjedő működést említ. Ez működési határ, nem állandó fűtőteljesítmény.')
 if p.get('ifeel'):features.append('<strong>A távirányító is segíthet a szabályozásban.</strong> Az I Feel funkció a távirányító érzékelőjét használja, ezért annak elhelyezése is számít.')
 if p.get('temper'):features.append('<strong>Temperálás.</strong> A 8 °C-os funkció alacsony hőmérsékletet tart egy ritkábban használt térben. A vízvezetékek fagyvédelmét ettől külön ellenőrizzük.')
 rows=[]
 keys=['Energia osztály','Wi-Fi vezérlés','Fűtésre optimalizált','Hatékonyság SCOP érték','Hűtőközeg','Beltéri egység mérete','Kültéri egység mérete']
 if p['power']:rows.append(('Teljesítmény a gyártói kínálatban',p['power']))
 if p['color']:rows.append(('Szín',p['color']))
 for k in keys:
  if k in par:rows.append((k,par[k]))
 if p['sku']:rows.append(('Típus / katalóguskód',p['sku']))
 spec=''.join(f'<div><dt>{E(k)}</dt><dd>{E(v)}</dd></div>'for k,v in rows)
 if not rows:spec='<div><dt>Pontos műszaki adatok</dt><dd>Személyes egyeztetéssel</dd></div>'
 docs=''.join(f'<a href="{E(d["url"])}" target="_blank" rel="noopener noreferrer">{E(d["label"])}</a>'for d in p['documents'])
 tags=''.join(f'<span>{E(t)}</span>'for t in [GROUPS[g],p['power'],p['color']]if t)
 image=f'<img src="../{E(p["image"])}" alt="{E(name)}" width="500" height="500">'if p.get('image')else '<p>C&amp;H</p>'
 warranty=par.get('Garancia','')
 warranty_html=f'<p class="small-note">A gyártói oldalon szereplő garancia: {E(warranty)}. A pontos jótállási feltételeket, a szükséges regisztrációt és karbantartást vásárlás előtt egyeztetjük.</p>'if warranty else ''
 general='A kW a készülék teljesítménye, nem az óránkénti villanyfogyasztás. A szoba mérete mellett a szigetelés, a tájolás és a használat is számít.'if g not in ['paratlanito','szellozes']else 'A megfelelő méretet a helyiség, a használat és az elhelyezési lehetőségek alapján választjuk ki.'
 energy='Az energiaosztályt a gyártói oldal jelölése szerint közöljük. A mérési körülmények és az üzemmód is számít; önmagában nem garantál fogyasztási értéket.'if 'Energia osztály'in par else ''
 s=header(name,summary(p),f'keszulekek/{p["slug"]}.html')+f'''<div class="wrap"><div class="breadcrumbs" style="padding-top:30px"><a href="../">Kezdőlap</a><span>›</span><a href="./">C&amp;H készülékek</a><span>›</span><span>{E(p['family'])}</span></div><section class="detail-hero"><div><p class="eyebrow">COOPER &amp; HUNTER · CSEFU KLÍMA</p><h1>{E(name)}</h1><div class="detail-tags">{tags}</div><p class="intro">{E(summary(p))}</p><a class="button" href="{E(inquire(p))}">Erről a készülékről kérek ajánlatot</a><p class="small-note" style="margin-top:18px">Csak készülékvásárláshoz is kérhet ajánlatot. Az aktuális ár és elérhetőség egyeztetés alapján.</p></div><figure class="detail-photo">{image}<figcaption>Gyártói termékfotó · C&amp;H magyar kínálat</figcaption></figure></section><section class="section detail-body"><div><p class="eyebrow">AMIT A MINDENNAPOKBAN ÉREZ</p><h2>Mit érdemes tudnia róla?</h2><ul class="readable-list">{''.join('<li>'+f+'</li>'for f in features)}</ul><div class="note-box"><strong>Segítünk jól választani.</strong><p>{E(general)}</p></div><p>A gondos telepítéshez az elhelyezést, a csővezetést és a műszaki előkészítést is átbeszéljük. <a class="text-link" href="../gondos-klimaszereles/">Így dolgozik Gyuri</a></p></div><div><p class="eyebrow">A LEGFONTOSABB ADATOK</p><h2>A választás kapaszkodói</h2><dl class="spec-list">{spec}</dl><p class="small-note" style="margin-top:16px">{E(energy)} Méreteknél az adatlap mértékegysége és sorrendje irányadó.</p>{warranty_html}<div class="documents">{docs}</div><p class="source-note">Forrás: <a href="{E(p['source'])}" target="_blank" rel="noopener noreferrer">C&amp;H magyar termékoldal</a> · Ellenőrizve: 2026. október 9. A gyártó módosíthatja a kínálatot és az adatokat; a pontos konfigurációt az ajánlatban rögzítjük.</p></div></section></div>'''+cta('Ez lehet az Ön készüléke?','Írja meg, hol és mire használná. A típust és a kivitelezést együtt egyeztetjük.',inquire(p),'Egyeztetek Gyurival')+footer()
 write('keszulekek/'+p['slug']+'.html',s)
for p in CAT:detail(p)
opts=lambda pairs:''.join(f'<option value="{E(v)}">{E(t)}</option>'for v,t in pairs)
fams=sorted(set(p['family']for p in CAT))
powers=sorted(set(p['power']for p in CAT if p['power']))
s=header('C&H készülékek, érthetően','A teljes ellenőrzött magyar Cooper & Hunter kínálat saját termékoldalakkal. Készülékvásárlás és gondos telepítés, személyes egyeztetéssel.','keszulekek/')+f'''<section class="catalog-intro"><div class="wrap"><div class="breadcrumbs"><a href="../">Kezdőlap</a><span>›</span><span>C&amp;H készülékek</span></div><p class="eyebrow">COOPER &amp; HUNTER · TELJES MAGYAR KÍNÁLAT</p><h1>Melyik illik<br>az Ön otthonához?</h1><p class="intro">{len(CAT)} készülékváltozat, közérthető saját adatlapokkal. Kezdje a split klímákkal, vagy válasszon más megoldást. Nem kell egyedül eligazodnia a típuskódok között.</p><a class="text-link" href="../#kapcsolat">Segítséget kérek a választáshoz</a></div></section><section class="section catalog-main wrap" aria-label="Készülékkatalógus"><div class="catalog-tools"><label for="catalog-search">Keresés név vagy típuskód alapján<input id="catalog-search" type="search" placeholder="Pl. Vital, Nature vagy CH-S12" autocomplete="off"></label><label for="catalog-group">Megoldás<select id="catalog-group"><option value="all">Minden megoldás</option>{opts(GROUPS.items()).replace('value="split"','value="split" selected')}</select></label><label for="catalog-family">Készülékcsalád<select id="catalog-family"><option value="all">Minden család</option>{opts((f,f)for f in fams)}</select></label><label for="catalog-power">Teljesítmény<select id="catalog-power"><option value="all">Minden teljesítmény</option>{opts((p,p)for p in powers)}</select></label></div><div class="catalog-toolbar"><span id="catalog-count" class="catalog-count" role="status" aria-live="polite">{len(CAT)} készülékváltozat</span><button id="catalog-reset" type="button">Minden szűrő törlése</button></div><noscript><p>JavaScript nélkül az összes készülék megjelenik, a szűrők nem működnek.</p></noscript><div id="catalog-empty" class="catalog-empty" hidden><h2>Erre nincs találat.</h2><p>Próbáljon kevesebb szűrőt, vagy kérjen segítséget Gyuritól.</p><a class="text-link" href="../#kapcsolat">Segítséget kérek</a></div><div class="catalog-grid">{''.join(card(p)for p in CAT)}</div><p class="source-note" style="margin-top:35px">A C&amp;H magyar oldalának lakossági, ipari és hőszivattyús kategóriái alapján, 2026. október 9-én ellenőrizve. A teljesítmény- és színváltozatok külön adatlapot kaptak. Az aktuális beszerezhetőséget és árat egyedi ajánlatban egyeztetjük.</p></section>'''+cta()+footer()
write('keszulekek/index.html',s)
# Three approachable choices on the homepage, with the full catalog one click away.
featured=[next(p for p in CAT if p['group']=='split'and p['family']==f and p['power']in ['3,2 kW','3,5 kW','3,51 kW']and p['color']in ['','fehér'])for f in ['Vital Plus','Arctic','Nature']]
home=ROOT/'index.html';s=home.read_text();s=re.sub(r'<div class="product-grid" id="featured-products">.*?(?=<div class="catalog-callout">)','<div class="product-grid" id="featured-products">'+''.join(card(p,'./').replace('<h2>','<h3>').replace('</h2>','</h3>')for p in featured)+'</div>\n',s,flags=re.S);home.write_text(s)
# Standalone campaign pages: no advertising scripts or tracking pixels are enabled.
LANDINGS={
 'gondos-klimaszereles':{
 'title':'A jó klíma a gondos szereléssel kezdődik.',
 'eyebrow':'KLÍMATELEPÍTÉS · INGYENES HELYSZÍNI FELMÉRÉS',
 'intro':'A készüléket minden nap használja. A szerelés részleteit viszont többnyire csak egyszer látja. Gyuri ezekre is ugyanazzal a gondossággal figyel, mintha a saját otthonában dolgozna.',
 'body':'''<article><h2>Az olcsó ajánlatból mi marad ki?</h2><p>Gyuri tapasztalata szerint sokan a készülék ára alapján döntenek, és csak később derül ki, hogy a választás vagy a kivitelezés nem illik az otthonukhoz. Egy kisebb vételár is lehet jó döntés — ha a készülék megfelelő, és a telepítés tartalma is rendben van.</p><p>Ezért előbb az igényt és a helyszínt nézzük meg. Hűtés vagy rendszeres fűtés? Nappali vagy hálószoba? Mennyi hely van a beltéri és a kültéri körül? Ezekből lesz használható ajánlat.</p></article><article><h3>Rézcsövezés, gondos kötések</h3><p>A Csefu réz hűtőközegcsövezéssel dolgozik. Gyuri nem alumínium–réz toldásokkal próbálja lefaragni az anyagköltséget. A megfelelő cső, a szigetelés és az ellenőrzött kötések a kivitelezés alapjai.</p></article><article><h3>A nyomvonal is az otthona része</h3><p>A látható csöveket és vezetékeket rendezett kábelcsatornában vezetjük, ahol a kialakítás ezt igényli. Az előre egyeztetett nyomvonal, a gondos faláttörés és a kondenzvíz elvezetése a kész végeredményhez tartozik.</p><p>A kábelcsatorna nem csupán látványelem: a megfelelően kialakított védelem és rögzítés is számít. Rejtett nyomvonalnál ugyanilyen figyelmet kap a műszaki kialakítás.</p></article><article><h3>Az elektromos háttér nem mellékes</h3><p>Már a felmérésen tisztázzuk, milyen betáplálást és előkészítést igényel a kiválasztott berendezés. Ha külön villanyszerelési munka szükséges, azt az ajánlat és az ütemezés részeként előre egyeztetjük.</p></article><article><h3>A beüzemelés több a bekapcsolásnál</h3><p>A kötések és a kondenzvíz-elvezetés ellenőrzése, a gyári előírások szerinti vákuumozás és a próbaüzem is a gondos átadáshoz tartozik. Megmutatjuk a kezelést, és átbeszéljük a karbantartást is.</p></article><div class="note-box"><h3>Ezt kérdezze meg minden ajánlatnál!</h3><ul class="checklist"><li>Pontosan melyik típust és teljesítményt kapom?</li><li>Milyen csőanyag és mekkora nyomvonal szerepel az árban?</li><li>Benne van a kábelcsatorna, a konzol és a faláttörés?</li><li>Hogyan oldják meg az áramellátást és a kondenzvizet?</li><li>Milyen ellenőrzést és beüzemelést végeznek?</li><li>Mi kerül külön pénzbe, és mik a jótállás feltételei?</li></ul></div><p class="source-note">A Csefu munkaszemlélete Gyuri tapasztalatai és a megrendelő által megadott információk alapján. A műszaki kialakítás mindig a kiválasztott készülék gyári előírásaihoz igazodik.</p>''',
 'cta':'Gondosan felszerelt klímát szeretnék'},
 'klima-futesre':{
 'title':'Klíma fűtésre? Válasszuk ki jól.',
 'eyebrow':'C&H HŰTŐ-FŰTŐ KLÍMÁK · SZEMÉLYES TERVEZÉS',
 'intro':'Átmeneti időben szeretne rásegíteni, vagy rendszeresen fűtene a klímával? Ezt érdemes már az első beszélgetésen tisztázni. A jó választás az otthonával kezdődik.',
 'body':'''<article><h2>A fűtésre való készülék és a jó méretezés együtt számít.</h2><p>A hűtő-fűtő klíma a külső levegőből nyert hőt adja át a helyiségnek. Hogy az Ön otthonában milyen megoldás válik be, azt a téli hőigény, a szigetelés, a helyiségek elrendezése és a használat alapján beszéljük át.</p><p>Nem elég, hogy egy készülék adatlapján szerepel a fűtés funkció. Rendszeres téli használatnál a hidegben rendelkezésre álló teljesítményt és az üzem feltételeit is vizsgáljuk.</p></article><article><h3>Mit jelent a hidegben megadott működési határ?</h3><p>Ha egy készülék például egy adott mínusz fokig működhet, az a működési tartomány határát jelzi. Nem azt ígéri, hogy minden kinti hőmérsékleten ugyanannyi hőt ad le. A megfelelő változatot ezért a téli igényhez méretezzük.</p></article><article><h3>Egy szobát vagy az egész otthont fűtené?</h3><p>Egy beltéri egység légárama nem jut el egyformán minden külön helyiségbe. A nyitott ajtó önmagában még nem jelent egyenletes fűtést. Több helyiséghez külön egységeket vagy multi rendszert is érdemes mérlegelni.</p></article><article><h3>A fogyasztási számok mögött is vannak feltételek</h3><p>A SCOP a fűtés szezonális hatékonyságának mutatója. Hasznos összehasonlítási pont, de a tényleges fogyasztást a hőigény, az időjárás, a beállítás és a telepítés is befolyásolja. Konkrét megtakarítást felmérés nélkül nem ígérünk.</p></article><article><h3>A kültéri elhelyezése és a víz útja is fontos</h3><p>Fűtéskor a kültéri egységnél is keletkezik víz, különösen leolvasztás során. Az elhelyezést és a vízelvezetést úgy tervezzük, hogy a téli használat szempontjai is helyet kapjanak az ajánlatban.</p></article><div class="note-box"><h3>Mit írjon meg Gyurinak?</h3><ul class="checklist"><li>Település, a fűteni kívánt helyiségek és alapterületük.</li><li>Milyen most a fűtés, és mire használná a klímát?</li><li>Milyen a szigetelés és a nyílászárók állapota?</li><li>Hol férhet el a beltéri és a kültéri egység?</li></ul></div><p><a class="button secondary" href="../keszulekek/?tipus=split">Megnézem a C&amp;H klímákat</a></p>''',
 'cta':'Fűtéshez kérek segítséget'},
 'klimatisztitas':{
 'title':'Gondos tisztítás. Kényelmesebb mindennapok.',
 'eyebrow':'KLÍMATISZTÍTÁS · KARBANTARTÁS · IDŐPONTFOGLALÁS',
 'intro':'Meglévő klímájával is keressen minket. A tisztítást és az ellenőrzést a berendezés állapotához igazítjuk, az időpontot pedig személyesen egyeztetjük.',
 'body':'''<article><h2>A karbantartás is része a kényelemnek.</h2><p>A rendszeresen használt klíma tisztítást és ellenőrzést igényel. Nemcsak az számít, amit a burkolaton lát: a berendezés belső részeinek állapota és a kondenzvíz megfelelő elvezetése is fontos.</p><p>A Csefu nyilvános oldalán prémium klímatisztítás, fertőtlenítés és karbantartás szerepel 13 990 Ft-os árral. Az Ön készülékére érvényes aktuális árat, a munka tartalmát és a kiszállás feltételeit foglalás előtt egyeztetjük.</p></article><article><h3>Mikor érdemes jelentkeznie?</h3><p>Ha eljött a szokásos karbantartás ideje, vagy a készülék működésén változást tapasztal. Kellemetlen szag, csöpögés vagy szokatlan zaj esetén az észlelt hibát is írja meg: a tisztítás és a hibajavítás eltérő feladat lehet.</p></article><article><h3>Mi történik az időpontkérés után?</h3><p>Az űrlap a klímatisztítás időpontfoglalására szolgál. A beküldés után telefonon egyeztetik a pontos érkezési időt. A megadott idősáv önmagában nem jelent visszaigazolt időpontot.</p></article><article><h3>Milyen gyakran kell tisztítani?</h3><p>A gyakoriságot a használat, a környezet és a gyártói előírások alapján érdemes meghatározni. A jótálláshoz kapcsolódó karbantartási feltételeket is vegye figyelembe.</p></article>''',
 'cta':'Karbantartásról kérdezek'} }
for slug,l in LANDINGS.items():
 s=header(l['title'],l['intro'],slug+'/')+f'''<section class="landing-hero"><div class="wrap"><div class="breadcrumbs"><a href="../">Kezdőlap</a><span>›</span><span>{E(l['eyebrow'].split(' · ')[0].title())}</span></div><p class="eyebrow">{E(l['eyebrow'])}</p><h1>{E(l['title'])}</h1><p class="intro">{E(l['intro'])}</p><div class="actions"><a class="button" href="{'#idopont'if slug=='klimatisztitas'else '../#kapcsolat'}">{'Időpontot kérek'if slug=='klimatisztitas'else E(l['cta'])}</a><span>Mintha magunknak csinálnánk.</span></div></div></section><section class="section wrap landing-body">{l['body']}'''
 if slug=='klimatisztitas':
  s+=f'''<div id="idopont" class="booking-box"><p class="eyebrow">BUDAPEST ÉS PEST VÁRMEGYE</p><h2>Klímatisztításra foglalok.</h2><p>Az időpontkérőben megadhatja az elérhetőségeit, a pontos címet, a készülékek számát és a megfelelő idősávot.</p><button class="button" type="button" data-load-form>Űrlap betöltése ezen az oldalon</button><a class="text-link" href="{FORM}" target="_blank" rel="noopener noreferrer">Űrlap megnyitása külön</a><p class="small-note">A beágyazott űrlap csak a betöltés gombra kattintás után kapcsolódik a Google szolgáltatásához. Az ott megadott adatokat a Google Forms és az űrlap tulajdonosa kezeli. Készülékvásárláshoz vagy általános kérdéshez <a href="../#kapcsolat">írjon Gyurinak</a>.</p><p id="booking-status" role="status" aria-live="polite"></p><iframe id="booking-frame" class="booking-frame" title="Csefu Klíma – klímatisztítás időpontfoglaló" data-src="{FORM}?embedded=true" hidden></iframe><noscript><p>Az űrlapot a külön megnyitási linkkel használhatja.</p></noscript></div>'''
 s+='</section>'+cta('Beszéljünk az Ön otthonáról.','Budapest és Pest vármegye. Országos projektek egyedi egyeztetéssel. Ingyenes helyszíni felmérés.',label=l['cta'])+footer()
 write(slug+'/index.html',s)
# Indexable static links, no fake prices, stock promises or customer reviews.
paths=['','keszulekek/']+[f'keszulekek/{p["slug"]}.html'for p in CAT]+[k+'/'for k in LANDINGS]
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE+p}</loc><lastmod>2026-10-09</lastmod></url>'for p in paths)+'</urlset>')
write('robots.txt','User-agent: *\nAllow: /\nSitemap: '+BASE+'sitemap.xml\n')
print('Generated',len(CAT),'product pages and',len(LANDINGS),'landing pages.')
